### ISSUE TITLE
Menu is not closing on touching anywhere outside the menu.

### ISSUE THREAD

**Issue by dineshjeyasankar** [caamorales/SphereMenuSwift#1]
Hi, I love this menu. How to close it when i touch anywhere outside the menu

**Comment by caamorales** [comment]
Hi Dinesh, I've updated the Menu so it can be dismissed by tapping outside the menu.  
Greetings from Colombia!

**Comment by dineshjeyasankar** [comment]
Thanks. It helped a lot.
